name: Josi Kosta
favicon: null
layout_spectrum: 0.6391357120592147
typography_spectrum: 0.5525339799933136
title: quite personal
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e2d3be'
    - '#b77243'
    - '#f2ac79'
    - '#411d0d'
    - '#774423'
  brandStrength: 0.375
  lightness: 0.626894416520372
  saturation: 0.8987601278349757
  rhythmicContrast: 0.7780293042305857
purpose: []
